- name: Update active realms
  uri:
    url: https://{{ proxy[0].host }}/service/rest/v1/security/realms/active
    method: PUT
    headers:
      content-type: 'application/json'
    user: admin
    password: "{{ admin_password }}"
    force_basic_auth: yes
    body_format: json
    body: '{{ payload | to_json() }}'
    validate_certs: '{{ validate_certs }}'
    status_code: 204
