version: '3.8'
services: 

  main:
    image: sonatype/nexus3:3.63.0
    volumes:
      - /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt
{% if nfs_host is defined %}
      - nexus-database:/nexus-data
{% else %}
      - {{ data_dir }}:/nexus-data
{% endif %}
    user: "${UID}:${GID}"
    deploy:
      labels:
        - traefik.enable=true

{% for item in proxy %}
        - traefik.http.services.{{ item.service }}.loadbalancer.server.port={{ item.port }}
        
        - traefik.http.routers.diesel-{{ item.router }}.rule=Host(`{{ item.diesel_host }}`)
        - traefik.http.routers.diesel-{{ item.router }}.service={{ item.service }}@docker
        - traefik.http.routers.diesel-{{ item.router }}.tls.certresolver=step-ca

        - traefik.http.routers.kiwi-{{ item.router }}.rule=Host(`{{ item.kiwi_host }}`)
        - traefik.http.routers.kiwi-{{ item.router }}.service={{ item.service }}@docker
        - traefik.http.routers.kiwi-{{ item.router }}.tls.certresolver=cloudflare
        - traefik.http.routers.kiwi-{{ item.router }}.tls.domains[0].main={{ '.'.join( item.kiwi_host.split('.')[1:] ) }}
        - traefik.http.routers.kiwi-{{ item.router }}.tls.domains[0].sans=*.{{ '.'.join( item.kiwi_host.split('.')[1:] ) }}
{% endfor %}


    networks:
      - {{ traefik_network }}

{% if nfs_host is defined %}
volumes:
  nexus-database:
    driver: local
    driver_opts:
      type: nfs
      o: addr={{ nfs_host }},rw,nfsvers=4,async
      device: :{{ nfs_path }}
{% endif %}

networks:
  {{ traefik_network }}:
    external:
      name: {{ traefik_network }}
