version: '3.8'
services: 

  main:
    image: sonatype/nexus3:3.41.0
    volumes:
      - /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt
      - {{ data_dir }}:/nexus-data/
    user: "${UID}:${GID}"
    deploy:
      labels:
        - traefik.enable=true

{% for item in proxy %}
        - traefik.http.services.{{ item.service }}.loadbalancer.server.port={{ item.port }}
        - traefik.http.routers.{{ item.router }}.rule=Host(`{{ item.host }}`)
        - traefik.http.routers.{{ item.router }}.service={{ item.service }}
        - traefik.http.routers.{{ item.router }}.tls.certresolver=step-ca
{% endfor %}

    networks:
      - {{ traefik_network }}
      
networks:
  {{ traefik_network }}:
    external:
      name: {{ traefik_network }}
