- name: Get {{ repo.format }} {{ repo.type }} repository `{{ repo.payload.name }}`
  uri:
    url: https://{{ proxy[0].diesel_host }}/service/rest/v1/repositories/{{ repo.format }}/{{ repo.type }}/{{ repo.payload.name }}
    method: GET
    headers:
      content-type: 'application/json'
    user: admin
    password: "{{ admin_password }}"
    force_basic_auth: yes
    validate_certs: '{{ validate_certs }}'
    status_code: 
      - 200
      - 404
  register: response

- name: response
  debug:
    msg: "{{ response }}"

- name: Remove repository `{{ repo.payload.name }}`
  uri:
    url: https://{{ proxy[0].diesel_host }}/service/rest/v1/repositories/{{ repo.payload.name }}
    method: DELETE
    headers:
      content-type: 'application/json'
    user: admin
    password: "{{ admin_password }}"
    force_basic_auth: yes
    validate_certs: '{{ validate_certs }}'
    status_code: 204
  when: response.status == 200
