- hosts: swarm_manager
  strategy: linear
  roles:
    - application
    - traefik
    - setup
    - configure_capabilities
    - configure_certificates
    - configure_ldap_connections
    - configure_cleanup_policies
    - configure_repositories
    - configure_anonymous_access
    - configure_active_realms
    - configure_privileges
    - configure_roles
    - configure_users
