- name: Configure anonymous access for `{{ payload.realmName }}`
  uri:
    url: https://{{ proxy[0].diesel_host }}/service/rest/v1/security/anonymous
    method: PUT
    headers:
      content-type: 'application/json'
    user: admin
    password: "{{ admin_password }}"
    force_basic_auth: yes
    body_format: json
    body: '{{ payload | to_json() }}'
    validate_certs: '{{ validate_certs }}'
    status_code: 200
