- name: Create capability `{{ payload.typeId }}`
  uri:
    url: https://{{ proxy.main.host }}/service/extdirect
    method: POST
    headers:
      content-type: 'application/json'
    user: admin
    password: "{{ admin_password }}"
    force_basic_auth: yes
    body_format: json
    body: '{{ payload | to_json() }}'
    validate_certs: '{{ validate_certs }}'
    status_code:
      - 200
      - 404
  register: response

- name: response
  debug:
    msg: "{{ response }}"
