- name: Get privilege `{{ privilege.payload.name }}`
  uri:
    url: https://{{ proxy[0].diesel_host }}/service/rest/v1/security/privileges/{{ privilege.payload.name }}
    method: GET
    headers:
      content-type: 'application/json'
    user: admin
    password: "{{ admin_password }}"
    force_basic_auth: yes
    validate_certs: '{{ validate_certs }}'
    status_code: 
      - 200
      - 404
  register: response

- name: response
  debug:
    msg: "{{ response }}"

- name: Create {{ privilege.type }} privilege `{{ privilege.payload.name }}`
  uri:
    url: https://{{ proxy[0].diesel_host }}/service/rest/v1/security/privileges/{{ privilege.type }}
    method: POST
    headers:
      content-type: 'application/json'
    user: admin
    password: "{{ admin_password }}"
    force_basic_auth: yes
    body_format: json
    body: '{{ privilege.payload | to_json() }}'
    validate_certs: '{{ validate_certs }}'
    status_code: 201
  when: response.status == 404

- name: Update {{ privilege.type }} privilege `{{ privilege.payload.name }}`
  uri:
    url: https://{{ proxy[0].diesel_host }}/service/rest/v1/security/privileges/{{ privilege.type }}/{{ privilege.payload.name }}
    method: PUT
    headers:
      content-type: 'application/json'
    user: admin
    password: "{{ admin_password }}"
    force_basic_auth: yes
    body_format: json
    body: '{{ privilege.payload | to_json() }}'
    validate_certs: '{{ validate_certs }}'
    status_code: 204
  when: response.status == 200
