proxy:
  
  - service: '{{ git_repository }}-{{ git_branch }}-main'
    port: 8081
    router: '{{ git_repository }}-{{ git_branch }}-main'
    host: nexus.dev.diesel.net
    
  - service: '{{ git_repository }}-{{ git_branch }}-docker'
    port: 8082
    router: '{{ git_repository }}-{{ git_branch }}-docker'
    host: docker.nexus.dev.diesel.net

  - service: '{{ git_repository }}-{{ git_branch }}-docker-proxy'
    port: 8083
    router: '{{ git_repository }}-{{ git_branch }}-docker-proxy'
    host: dockerhub.nexus.dev.diesel.net
