ldap_password: "{{ lookup('env', 'LDAP_ADMIN_PASSWORD') }}"

ldap_connections:

  - name: diesel-ldap
    protocol: LDAPS
    useTrustStore: true
    host: ldap.diesel.net
    port: 636
    searchBase: dc=diesel,dc=net
    authScheme: SIMPLE # enum: NONE, SIMPLE, DIGEST_MD5, CRAM_MD5
    authRealm: ''
    authUsername: cn=admin,dc=diesel,dc=net
    authPassword: '{{ ldap_password }}'
    connectionTimeoutSeconds: 30
    connectionRetryDelaySeconds: 300
    maxIncidentsCount: 3
    userBaseDn: ou=users
    userSubtree: true
    userObjectClass: posixAccount
    userLdapFilter:
    userIdAttribute: uid
    userRealNameAttribute: cn
    userEmailAddressAttribute: mail
    userPasswordAttribute:
    ldapGroupsAsRoles: true
    groupType: DYNAMIC #enum STATIC, DYNAMIC
    groupBaseDn: ou=groups
    groupSubtree: true
    groupObjectClass: ''
    groupIdAttribute: ''
    groupMemberAttribute: ''
    groupMemberFormat: ''
    userMemberOfAttribute: memberOf
